# Generated by Django 2.2.9 on 2023-02-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='groups',
            field=models.TextField(blank=True, null=True),
        ),
    ]
